version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: events
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
